### ISSUE TITLE
Improve the Developer User Experience of the DICOMcloud library

### ISSUE THREAD

**Issue by Zaid-Safadi** [Zaid-Safadi/DICOMcloud#25]
Since the initial development of the DICOMcloud library and the focus has been to add and support as many features possible defined in the DICOMweb protocol to provide a reference implementation as a standalone DICOMweb Server. 

I’ve been trying lately to improve the user experience working with the library, understanding the functionality and API, how to run a development environment and deployment.
In order to track the status of these activities in a single place, I’ll be adding here the related issue’s title with a link and any work that is yet to be done. Any suggestions are welcome!

- [ ] Create Nuget packages for the library to bootstrap development #26  
- [x] Simplify running the WADO Server from Visual Studio #24
- [x] Implement a versioning mechanism for the library #23
- [x] Create an ARM template with deploy to Azure button #19
- [x] Create unit test projects to cover the different examples of using the library #18
- [x] Add API documentation using Swagger #12
- [x] Create a SQL Server database project to maintain the DICOM server database and publish to SQL server #8
